# Vector Algebra

Vectors are basically a list of numbers. They are used to represent a point in space, a direction, a force, or really anything that can be represented by a list of numbers.

## Basic Vectors

We use a library called `numpy` to represent vectors. It is a very powerful library that implements true arrays (not lists) and a lot of linear algebra functions.

In [3]:
import numpy as np

# Create a vector as a row
vector_row = np.array([1, 2, 3])

# Create a vector as a column

vector_column = np.array([[1],[2],[3]])

print(vector_row)
print(vector_column)

[1 2 3]
[[1]
 [2]
 [3]]


In [6]:
a = np.array([[1,2,3],[4,5,6],[7,8,9]])

b = np.array([[1,2,3],[4,5,6],[7,8,9]])

c = (a@b).transpose()

print(c)

[[ 30  66 102]
 [ 36  81 126]
 [ 42  96 150]]


## Solving AX = B

We can use the `numpy.linalg.solve` function to solve the equation $AX = B$ for $X$.

But, to sort of understand what is going on, we can also solve it by hand using the gaussian elimination method.

Gaussion elimination is a method of solving a system of linear equations by reducing the matrix to row echelon form and then back substituting to find the values of the variables.

But, for now, to find the X, we just do `numpy.linalg.solve(A, B)` 
or we can also do it with $A^{-1}B$.

In [8]:
a = np.array([[4, 2, 4], [5, 3, 7], [9, 3 ,6]])

b = np.array([44, 56, 72])

x = np.linalg.inv(a).dot(b)

print(x)

[ 2. 34. -8.]


## Eigen Values and Eigen Vectors

Eigen values are the values of the matrix that when multiplied with the eigen vector, give the same vector back.

$Av = \lambda v$

Hence, they are essentially a decomposition of the matrix into its eigen vectors and eigen values. They are hence also called the characteristic values and characteristic vectors.

In [9]:
import numpy as np

a = np.array([[1,2], [3,4]])

eigenvalues, eigenvectors = np.linalg.eig(a)

print(eigenvalues)
print(eigenvectors)

[-0.37228132  5.37228132]
[[-0.82456484 -0.41597356]
 [ 0.56576746 -0.90937671]]


Now, by definition, 
$Q \lambda Q^{-1} = A$

In [11]:
b = eigenvectors @ np.diag(eigenvalues) @ np.linalg.inv(eigenvectors)

print(b)

[[1. 2.]
 [3. 4.]]


# Problems

In [12]:
import numpy as np

In [13]:
A = np.array([[3, 1, 0], [2, 4, 1], [3, 1, 8]])
B = np.array([54, 12, 6])

X = np.linalg.inv(A).dot(B)

print(X)

[19.8 -5.4 -6. ]
